name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          python3-virtualenv \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          zlib1g-dev \
          pkg-config \
          autoconf \
          automake \
          libtool \
          cmake

    - name: Install Python packages
      run: |
        pip install --upgrade pip
        pip install cython==0.29.36 buildozer

    - name: Initialize Buildozer
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: TradingApp-APK
        path: bin/*.apk
